### ISSUE TITLE
[Bug] Everything插件在首次遍历磁盘时，使用搜索就会崩溃

### ISSUE THREAD

**Issue by emako** [OrgEleCho/CurvaLauncher#10]
Version：v0.6.1-beta

**Comment by SlimeNull** [comment]
我去逝逝bug, 其实这边编写的时候也遇到过一些崩溃, 后来换了个托管的 Everything 通信库, 暂时没出问题就没注意过了

**Comment by SlimeNull** [comment]
我还发现个问题, 在 Everything 建立索引的时候, 使用 CurvaLauncher 搜索, 即便用 try 捕捉了异常, 在下一次搜索时也没办法得到结果... 可能是通信库上面的问题...
