### ISSUE TITLE
[feature] 搜索应用名时，支持以文件名的搜索

### ISSUE THREAD

**Issue by emako** [OrgEleCho/CurvaLauncher#11]
搜索应用名时，支持以文件名(xxx.exe)搜索

for example，

通过安装包安装了百度网盘。
然后【百度】关键字能搜索到，但其实应用文件名是baidunetdisk.exe却无法通过【baidu】关键字搜到。

![image](https://github.com/OrgEleCho/CurvaLauncher/assets/24737061/32a7fed7-7227-4331-aeb6-1d9005be4f3c)

**Comment by Gn3po4g** [comment]
感觉可以添加基于everything的搜索功能

**Comment by SlimeNull** [comment]
可以

**Comment by SlimeNull** [comment]
不过目前是支持拼音搜索的, 你可以暂时用着. 在设置页面启用拼音搜索即可.

**Comment by SlimeNull** [comment]
已添加功能支持, 在不久后会发布新版本供使用 `[]~(￣▽￣)~*`
