### ISSUE TITLE
输入框内容为空时, 按上下方向键程序会报错无响应。

### ISSUE THREAD

**Issue by ayumi043** [OrgEleCho/CurvaLauncher#2]
![1704955095040](https://github.com/OrgEleCho/CurvaLauncher/assets/165910/9ab80bd2-42da-4891-920d-9e11afd28403)

**Comment by SlimeNull** [comment]
趣, 忘记做校验了, 等我把手里的代码写差不多了就改

**Comment by SlimeNull** [comment]
好了, 最新版本已修复
