### ISSUE TITLE
[feature] 能否支持ctrl+alt作为呼出键？

### ISSUE THREAD

**Issue by emako** [OrgEleCho/CurvaLauncher#8]

**Comment by SlimeNull** [comment]
貌似不行, 目前快捷键是基于 WinAPI 的 RegisterHotkey 做的

**Comment by SlimeNull** [comment]
而且, 就算可以, 假如你想使用另外某个程序的 Ctrl+Alt+X 快捷键, 而 CurvaLauncher 被打开了, 这不就是奇怪的行为了吗? 所以这个需求, 不太合理.

**Comment by SlimeNull** [comment]
hmmm, 从技术上我暂时想不到如何用较好的方式实现 Ctrl+Alt 呼出, 虽然也可以直接判断物理按键是否按下, GetAsyncKeyState 啥的, 但是这种方式并不优雅所以并不想这样实现. 你可以尝试 PR

**Comment by emako** [comment]
如果 Hotkey 本身不支持 ctrl+alt，那就只能判断键盘了，或则更复杂点的RawInput。

目前还是先保持CurvaLauncher的瘦小吧。
后续如果需要可参考我写的 https://github.com/babalae/better-genshin-impact/tree/main/Fischless.KeyboardCapture

**Comment by SlimeNull** [comment]
有个 WinAPI, 就我说的 GetAsyncKeyState, 拿物理按键状态的 API.
